package com.rqueztech.ui.enums;

public enum MainLoginPanelEnums {
	USERNAME_LABEL_KEY,
	USERNAME_TEXTFIELD_KEY,
	PASSWORD_LABEL_KEY,
	PASSWORD_TEXTFIELD_KEY,
	VISIBILITY_BUTTON_KEY,
	USER_LOGIN_BUTTON_KEY,
	ADMIN_LOGIN_BUTTON_KEY;
}
