package com.rqueztech.ui.configuration.enums;

public enum SetupConfigurationPanelEnums {
	FIRSTNAME_LABEL_KEY,
	FIRSTNAME_TEXTFIELD_KEY,
	LASTNAME_LABEL_KEY,
	LASTNAME_TEXTFIELD_KEY,
	EXIT_BUTTON_KEY,
	SUBMIT_BUTTON_KEY,
	PASSPHRASE_LABEL_KEY,
	PASSPHRASE_TEXTFIELD_KEY,
	PASSPHRASE_VISIBILITY_BUTTON_KEY,
	CONFIRM_PASSPHRASE_LABEL_KEY,
	CONFIRM_PASSPHRASE_TEXTFIELD_KEY,
	CONFIRM_PASSPHRASE_VISIBILITY_BUTTON_KEY,
	PASSWORD_LABEL_KEY,
	PASSWORD_TEXTFIELD_KEY,
	PASSWORD_VISIBILITY_BUTTON_KEY,
	CONFIRM_PASSWORD_LABEL_KEY,
	CONFIRM_PASSWORD_TEXTFIELD_KEY,
	CONFIRM_PASSWORD_VISIBILITY_BUTTON_KEY;
}
