package com.rqueztech.ui.admin.enums;

public enum AdminAddUserEnums {
	FIRSTNAME_LABEL_KEY,
	FIRSTNAME_TEXTFIELD_KEY,
	LASTNAME_LABEL_KEY,
	LASTNAME_TEXTFIELD_KEY,
	CANCEL_BUTTON_KEY,
	ADD_USER_BUTTON_KEY,
	PASSPHRASE_LABEL_KEY,
	PASSPHRASE_TEXTFIELD_KEY,
	PASSPHRASE_VISIBILITY_BUTTON_KEY;
}
