package com.rqueztech.ui.admin.enums;

public enum AdminUserViewEnums {
		CONFIRMPASSWORDPASSWORD_LABEL_KEY,
		DELETE_USER_BUTTON_KEY,
		RETURN_CENTRAL_BUTTON_KEY,
		ADMIN_LOGOUT_BUTTON_KEY,
		ADD_USER_BUTTON_KEY,
		RETURN_CENTRAL_TEXTFIELD_KEY;
}
