package com.rqueztech.ui.user.enums;

public enum UserChangeDefaultPasswordEnums {
	ENTERPASSWORD_LABEL_KEY,
	ENTERPASSWORD_TEXTFIELD_KEY,
	ENTERPASSWORD_VISIBILITY_BUTTON_KEY,
	CONFIRMPASSWORDPASSWORD_LABEL_KEY,
	CONFIRMPASSWORDPASSWORD_TEXTFIELD_KEY,
	CONFIRMPASSWORD_VISIBILITY_BUTTON_KEY,
	CANCEL_CHANGE_BUTTON_KEY,
	SUBMIT_LOGIN_BUTTON_KEY;
}
