package main.com.rqueztech.ui.configuration.enums;

/**
 * The SetupConfigurationPanelEnums enumeration represents the keys for]
 various components on the setup configuration panel. These keys are used to
 manipulate the corresponding components in the user interface.
 */
public enum SetupConfigurationPanelEnums {
  FIRSTNAMELABELKEY,
  FIRSTNAMETEXTFIELDKEY,
  LASTNAMELABELKEY,
  LASTNAMETEXTFIELDKEY,
  EXITBUTTONKEY,
  SUBMITBUTTONKEY,
  PASSPHRASELABELKEY,
  PASSPHRASETEXTFIELDKEY,
  PASSPHRASEVISIBILITYBUTTONKEY,
  CONFIRMPASSPHRASELABELKEY,
  CONFIRMPASSPHRASETEXTFIELDKEY,
  CONFIRMPASSPHRASEVISIBILITYBUTTONKEY,
  PASSWORDLABELKEY,
  PASSWORDTEXTFIELDKEY,
  PASSWORDVISIBILITYBUTTONKEY,
  CONFIRMPASSWORDLABELKEY,
  CONFIRMPASSWORDTEXTFIELDKEY,
  CONFIRMPASSWORDVISIBILITYBUTTONKEY;
}
